"""add columns

Revision ID: 183ffd8c8b42
Revises: 
Create Date: 2025-05-05 16:30:41.752574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183ffd8c8b42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plan_status', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('activation_date', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('activation_end_date', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.create_foreign_key(None, 'plans', ['plan_id'], ['plan_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('activation_end_date')
        batch_op.drop_column('activation_date')
        batch_op.drop_column('plan_status')
        batch_op.drop_column('plan_id')

    # ### end Alembic commands ###
